services:
  - type: web
    name: nexus-wallet
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: RENDER
        value: "true"
      - key: APP_PASSWORD
        value: "090902"
      - key: SESSION_SECRET
        value: "super-secret-key-nexus-v3"
